### ISSUE TITLE
Integration not working

### ISSUE THREAD

**Issue by rvilvert** [rokam/sunweg#11]
I'm receiving the following warning:
`Updating sunweg sensor took longer than the scheduled update interval 0:00:30`

If I reload the integration it will update the data once, but later this happen.

sunweg - latest version
HA Core 2024.5.3
HA Frontend 20240501.1

Anything I could do to check what is going on?

Thanks

Raphael

**Comment by rokam** [comment]
There is a PR at HA so fix that: https://github.com/home-assistant/core/pull/118435
Please can you submit an issue there?
